/**
 * Created by s70c3 on 12.02.17.
 */

//Rooms
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOM_SUCCESS= 'GET_ROOM_SUCCESS';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export  const  ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS';
export  const  ADD_OCCUPATION_SUCCESS = 'ADD_OCCUPATION_SUCCESS';
export  const  GET_OCCUPATIONS_SUCCESS = 'ADD_OCCUPATION_SUCCESS';
export const SET_DATE ='SET_DATE';